version: '3'

# --- VOLÚMENES NUEVOS (Separados de tu backend original) ---
volumes:
  recsa_general_postgres_data: {} 
  recsa_general_postgres_data_backups: {}
  recsa_general_redis_data: {}

services:
  # --- BACKEND (Django) ---
  django: &django
    build:
      context: ./backend
      dockerfile: ./compose/local/django/Dockerfile
    image: recsa_challenge_local_django
    container_name: recsa_challenge_local_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./backend/.envs/.local/.django
      - ./backend/.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: ./backend
      dockerfile: ./compose/production/postgres/Dockerfile
    image: recsa_challenge_production_postgres
    container_name: recsa_challenge_local_postgres
    volumes:
      # AQUÍ ESTÁ EL CAMBIO: Usamos los volúmenes "general" nuevos
      - recsa_general_postgres_data:/var/lib/postgresql/18/docker
      - recsa_general_postgres_data_backups:/backups
    env_file:
      - ./backend/.envs/.local/.postgres

  redis:
    image: docker.io/redis:7.2
    container_name: recsa_challenge_local_redis
    volumes:
      # También separamos el caché de Redis
      - recsa_general_redis_data:/data

  # --- WORKERS (Heredan de django) ---
  celeryworker:
    <<: *django
    image: recsa_challenge_local_celeryworker
    container_name: recsa_challenge_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: recsa_challenge_local_celerybeat
    container_name: recsa_challenge_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: recsa_challenge_local_flower
    container_name: recsa_challenge_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  # --- FRONTEND (React) ---
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: recsa_challenge_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - django